- hosts: myhost 
  become: true
  become_method: sudo
  tasks:
   - name: Install all the packages
     apt:
         name: ['cowsay','sockstat', 'fortune', 'curl', 'git', 'vim', 'htop', 'iftop', 'telnet', 'openssh-client', 'ecryptfs-utils', 'cryptsetup', 'clamav', 'clamav-daemon', 'thefuck', 'keepassxc', 'wget']
         state: present
         update_cache: True
         force_apt_get: True
